server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    username:
    password:
    url: jdbc:postgresql://localhost:5432/cloud_fraud
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka